CREATE DATABASE library CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE library;

CREATE TABLE USERS (
 Id INT NOT NULL PRIMARY KEY,
 Passwd VARCHAR(64) NOT NULL,
 name VARCHAR(30) NOT NULL,
 created_at DATE NOT NULL
);

CREATE TABLE BOOK (
	ISBN INT NOT NULL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	publisher VARCHAR(30),
	writer VARCHAR(30),
	category VARCHAR(30),
	lib_row INT NOT NULL,
	lib_cal INT NOT NULL,
	created_at DATE
);	

CREATE TABLE BOOKS (
	Id INT NOT NULL PRIMARY KEY,
	ISBN INT NOT NULL,
	FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE RENTAL(
	Number INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	Users_Id INT NOT NULL,
	Books_Id INT NOT NULL,
	rental_at DATETIME NOT NULL,
	return_at DATETIME NOT NULL,
	return_flag TINYINT(1) NOT NULL,
	FOREIGN KEY(Users_Id) REFERENCES USERS(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Books_Id) REFERENCES BOOKS(Id) ON DELETE RESTRICT ON UPDATE CASCADE
);